In [1]:
import numpy as np

In [47]:

# np.linspace(0,5,4)          """""" Ratioo nikal ta ha Ex. 10 person 5 cap distribution karna""

# Any                             kya na  koi 6 foot (height) se jada hai   agar        OUTPUT: True 

# all                                    Sabhi ki  6 foot (height) se jada hai   

      # we will use Temperature dataset  (all  + any )

#np.where(k==6)                         # where 6 vale  kis index ?    

#np.insert(k,2,88)       # Insert method  adding element not permanet save ,please save variable, Numpy  inmutable hota hai

#h=np.vstack((b,c))
                """""" vertical shape me add karna """"""
    
#h=np.Hstack((b,c))
                """"""Horizontal  shape me Convert karna """"""    

IndentationError: unexpected indent (1551326280.py, line 14)

In [2]:
a=np.array([[4,5,6],[2,3,3],[1,8,7]])
a

array([[4, 5, 6],
       [2, 3, 3],
       [1, 8, 7]])

In [3]:
b=np.array([[4,5,6],[1,2,3],[4,2,1]])
b

array([[4, 5, 6],
       [1, 2, 3],
       [4, 2, 1]])

In [4]:
b[:2,0:3]

array([[4, 5, 6],
       [1, 2, 3]])

In [5]:
np.linspace(0,5,4)     # Ratioo nikal ta ha                     Ex. 10 person 5 cap distribution karna 

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [6]:
b

array([[4, 5, 6],
       [1, 2, 3],
       [4, 2, 1]])

In [8]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
# Any        kya na  koi 6 foot (height) se jada hai   agar        OUTPUT: True 

# all        Sabhi ki  6 foot (height) se jada hai   


# we will use Temperature dataset 
# 




np.any(b>3)




True

In [12]:
 np.all(b>0)       

True

In [13]:
b

array([[4, 5, 6],
       [1, 2, 3],
       [4, 2, 1]])

In [14]:
k=np.array([4,5,6,7])
k

array([4, 5, 6, 7])

In [15]:
k2=np.array([3,2,7,4])
k2

array([3, 2, 7, 4])

In [17]:
np.equal(k,k2).any()      # Index pe Macth karta hai

False

In [18]:
np.equal(k,k2).all()      # Index pe Macth karta ha

False

In [19]:
b

array([[4, 5, 6],
       [1, 2, 3],
       [4, 2, 1]])

In [20]:
b.ndim

2

In [21]:
b.shape

(3, 3)

In [24]:
j=np.array([[3,4],[1,2],[6,7]])
j

array([[3, 4],
       [1, 2],
       [6, 7]])

In [25]:
j.shape

(3, 2)

In [26]:
p=np.array([[[5,6,7],[1,2,3],[7,5,4]]])
p

array([[[5, 6, 7],
        [1, 2, 3],
        [7, 5, 4]]])

In [27]:
p.ndim

3

In [28]:
p.shape

(1, 3, 3)

In [29]:
k2

array([3, 2, 7, 4])

In [32]:
np.where(k==6)     #   where kaha 6 kis index ?

(array([2], dtype=int64),)

In [31]:
k

array([4, 5, 6, 7])

In [34]:
np.insert(k,2,88)     # Insert method  adding element not permanet save       please save variable 

                        # Numpy  inmutable hota hai

array([ 4,  5, 88,  6,  7])

In [35]:
t=np.insert(k,2,88)     
t


array([ 4,  5, 88,  6,  7])

In [36]:
k

array([4, 5, 6, 7])

In [37]:
k[::-1]

array([7, 6, 5, 4])

In [38]:
b

array([[4, 5, 6],
       [1, 2, 3],
       [4, 2, 1]])

In [39]:
c=np.array([[2,3,1],[3,6,7],[1,1,2]])
c

array([[2, 3, 1],
       [3, 6, 7],
       [1, 1, 2]])

In [42]:
h=np.vstack((b,c))
h                       #  vertical shape me add karna 

array([[4, 5, 6],
       [1, 2, 3],
       [4, 2, 1],
       [2, 3, 1],
       [3, 6, 7],
       [1, 1, 2]])

In [41]:
h.shape

(6, 3)

In [45]:
u=np.hstack((b,c))
u                   #  Horizantal shape me convert karna 

array([[4, 5, 6, 2, 3, 1],
       [1, 2, 3, 3, 6, 7],
       [4, 2, 1, 1, 1, 2]])

In [46]:
u.shape

(3, 6)