In [1]:
import numpy as np

In [2]:
a=np.array([45,11,4,5,6,7,3,2,1])
a

array([45, 11,  4,  5,  6,  7,  3,  2,  1])

In [2]:
a.ndim 

NameError: name 'a' is not defined

In [4]:
type(a)

numpy.ndarray

In [5]:
a.dtype

dtype('int32')

In [6]:
len(a)

9

In [51]:
b=np.array([3,5,6,1,2,3,9,18,4,2,6,7])

In [11]:
np.sum(b)

59

In [13]:
np.max(b)

18

In [10]:
np.min(b)

1

In [14]:
np.median(b)

4.0

In [15]:
np.mean(b)

5.363636363636363

In [16]:
np.std(b)

4.558164049716972

In [17]:
np.var(b)

20.776859504132233

In [19]:
np.sqrt(b)

array([1.73205081, 2.23606798, 2.44948974, 1.        , 1.41421356,
       1.73205081, 3.        , 4.24264069, 2.        , 1.41421356,
       2.44948974])

In [20]:
np.cbrt(b)

array([1.44224957, 1.70997595, 1.81712059, 1.        , 1.25992105,
       1.44224957, 2.08008382, 2.62074139, 1.58740105, 1.25992105,
       1.81712059])

In [21]:
b

array([ 3,  5,  6,  1,  2,  3,  9, 18,  4,  2,  6])

In [22]:
np.sort(b)

array([ 1,  2,  2,  3,  3,  4,  5,  6,  6,  9, 18])

In [23]:
b[2:6]

array([6, 1, 2, 3])

In [24]:
b[::-1]

array([ 6,  2,  4, 18,  9,  3,  2,  1,  6,  5,  3])

In [25]:
b[-1]

6

In [26]:
b[0]

3

In [27]:
len(b)

11

In [28]:
c=np.array([5,6,7,8,1,2,8,5,43,2,8])
c

array([ 5,  6,  7,  8,  1,  2,  8,  5, 43,  2,  8])

In [29]:
len(c)

11

In [30]:
r=[7,8,9]
r

[7, 8, 9]

In [31]:
r2=[3,4,5]
r2

[3, 4, 5]

In [32]:
g=list(map(lambda x,y:x+y,r,r2))
g

[10, 12, 14]

In [33]:
f=np.array([3, 4, 5])
f


array([3, 4, 5])

In [34]:
f2=np.array([7,8,9]
)
f2

array([7, 8, 9])

In [35]:
f+f2

array([10, 12, 14])

In [36]:
r2

[3, 4, 5]

In [37]:
t=np.array([10000,20000,30000,40000,50000,60000,70000])

In [41]:
k=t*18/100

In [42]:
k-2000

array([ -200.,  1600.,  3400.,  5200.,  7000.,  8800., 10600.])

In [43]:
b

array([ 3,  5,  6,  1,  2,  3,  9, 18,  4,  2,  6])

In [44]:
f

array([3, 4, 5])

In [45]:
f2

array([7, 8, 9])

In [46]:
np.add(f,f2)

array([10, 12, 14])

In [47]:
np.multiply(f,f2)

array([21, 32, 45])

In [48]:
np.divide(f,f2)

array([0.42857143, 0.5       , 0.55555556])

In [52]:
b

array([ 3,  5,  6,  1,  2,  3,  9, 18,  4,  2,  6,  7])

In [53]:
len(b)

12

In [54]:
b.ndim

1

In [55]:
h=np.reshape(b,(4,3))
h

array([[ 3,  5,  6],
       [ 1,  2,  3],
       [ 9, 18,  4],
       [ 2,  6,  7]])

In [56]:
h.ndim

2

In [57]:
h.shape

(4, 3)

# Transform karna 

In [58]:
h.T

array([[ 3,  1,  9,  2],
       [ 5,  2, 18,  6],
       [ 6,  3,  4,  7]])

In [59]:
h[0]

array([3, 5, 6])

In [60]:
h[2][1]

18

In [ ]:
#  mean 
#  meaian 
#  mode 
# variance
# sqrt
# cbrt

# shape  Reshape    +  TransFrom karna row  coloumn  ko 

# (Sum ,  sub  , divide, multiply )

# slicing
# Percentage %

# Sort sorting karna data ko 

