In [1]:
import numpy as np

In [6]:
a=np.array([[4,5,6],[2,3,3],[1,8,7]])
a

array([[4, 5, 6],
       [2, 3, 3],
       [1, 8, 7]])

In [7]:
a[::,::-1]   # row  ::     #  coloumn ::

array([[6, 5, 4],
       [3, 3, 2],
       [7, 8, 1]])

In [8]:
a[::-1,::-1]    # row ::    # column ::  dono  ko exchange karna 

array([[7, 8, 1],
       [3, 3, 2],
       [6, 5, 4]])

In [9]:
a

array([[4, 5, 6],
       [2, 3, 3],
       [1, 8, 7]])

In [10]:
a[0:2,1:3]       #  5, 6
                 #  3, 3

array([[5, 6],
       [3, 3]])

In [11]:
a

array([[4, 5, 6],
       [2, 3, 3],
       [1, 8, 7]])

In [12]:
b=np.array([[4,5,6],[1,2,3],[4,2,1]])
b

array([[4, 5, 6],
       [1, 2, 3],
       [4, 2, 1]])

In [13]:
a*b

array([[16, 25, 36],
       [ 2,  6,  9],
       [ 4, 16,  7]])

In [ ]:
# Broadcasting karta hai  ( *  + -  / )

In [14]:
a-b

array([[ 0,  0,  0],
       [ 1,  1,  0],
       [-3,  6,  6]])

In [15]:
a+b

array([[ 8, 10, 12],
       [ 3,  5,  6],
       [ 5, 10,  8]])

In [16]:
a/b

array([[1.  , 1.  , 1.  ],
       [2.  , 1.5 , 1.  ],
       [0.25, 4.  , 7.  ]])

# Vector ?

In [17]:
a

array([[4, 5, 6],
       [2, 3, 3],
       [1, 8, 7]])

In [18]:
b

array([[4, 5, 6],
       [1, 2, 3],
       [4, 2, 1]])

In [19]:
a*b

array([[16, 25, 36],
       [ 2,  6,  9],
       [ 4, 16,  7]])

In [21]:
np.dot(a,b)

array([[45, 42, 45],
       [23, 22, 24],
       [40, 35, 37]])

# Metrix  ka Determination ?


In [23]:
np.linalg.det(a)

11.000000000000002

In [24]:
np.linalg.inv(a)

array([[-2.72727273e-01,  1.18181818e+00, -2.72727273e-01],
       [-1.00000000e+00,  2.00000000e+00, -4.11193713e-18],
       [ 1.18181818e+00, -2.45454545e+00,  1.81818182e-01]])

# Metrix rank ?

In [25]:
np.linalg.matrix_rank(a)

3

In [26]:
np.linalg.matrix_power(a,2)   # Metrix ki power nikalna ?

array([[32, 83, 81],
       [17, 43, 42],
       [27, 85, 79]])

In [27]:
a

array([[4, 5, 6],
       [2, 3, 3],
       [1, 8, 7]])

In [28]:
b

array([[4, 5, 6],
       [1, 2, 3],
       [4, 2, 1]])

# Flatten ?

In [29]:
b.flatten()

array([4, 5, 6, 1, 2, 3, 4, 2, 1])

In [30]:
# 28  +  29,                                 2 d  to   1 d    array convert 

In [31]:
np.union1d(a,b)                                                  #  multiple metrix me unique  value output                     

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
a

array([[4, 5, 6],
       [2, 3, 3],
       [1, 8, 7]])

In [33]:
np.unique(a)                                                     #  single metrix me uniqe value naikalna 

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
a

array([[4, 5, 6],
       [2, 3, 3],
       [1, 8, 7]])

In [35]:
np.sum(a)

39

In [36]:
np.max(a)

8

In [37]:
np.min(a)

1

Row    wise    sum   karna 

In [38]:
a

array([[4, 5, 6],
       [2, 3, 3],
       [1, 8, 7]])

In [42]:
np.sum(a,axis=0)    #     axis=0  column   wise 

array([ 7, 16, 16])

In [43]:
np.sum(a,axis=1)    #     axis=1  Row   wise 

array([15,  8, 16])

In [44]:
np.max(a,axis=1)      

array([6, 3, 8])

In [45]:
np.max(a,axis=0)

array([4, 8, 7])